# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('profile_image', models.ImageField(max_length=128, upload_to='')),
                ('bio', models.TextField()),
                ('department', models.CharField(choices=[('ACC', 'Account Management'), ('DEV', 'Developer'), ('DES', 'Designer'), ('QUA', 'Quality Assurance'), ('OPE', 'Operations'), ('STR', 'Strategy'), ('LEA', 'Leadership'), ('TRA', 'Trafficing'), ('DPS', 'IT & Devops')], max_length=3)),
                ('title', models.CharField(max_length=96)),
                ('team_group', models.CharField(choices=[('RED', 'Red Team'), ('BLU', 'Blue Team'), ('YEL', 'Yellow Team'), ('GRE', 'Green Team'), ('PUR', 'Purple Team'), ('GRE', 'Grey Team')], max_length=3)),
                ('twitter_handle', models.CharField(max_length=96)),
                ('overwatch_handle', models.CharField(max_length=96)),
                ('instagram_handle', models.CharField(max_length=96)),
                ('pinterest_handle', models.CharField(max_length=96)),
                ('steam_handle', models.CharField(max_length=96)),
            ],
        ),
    ]
