# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='overwatch_handle',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='pinterest_handle',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='steam_handle',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=96),
        ),
    ]
