# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170421_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_image',
            field=models.ImageField(max_length=128, upload_to='profiles/'),
        ),
    ]
