# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0002_auto_20170330_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetrackers',
            old_name='name',
            new_name='project_name',
        ),
    ]
