# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resources_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
