# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20170401_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profiles'),
        ),
    ]
