# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20170410_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profiles'),
        ),
    ]
