# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20170410_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resources_group',
            field=models.CharField(blank=True, choices=[('Statement of Work / Legal', [('CAG', 'Consulting Services Agreement'), ('FAG', 'Facility License Agreement'), ('MAG', 'Master Services Agreement'), ('NAG', 'Non-Disclosure Agreement (NDA)'), ('OTH', 'Other')]), ('Project Process', [('KOF', 'Kick Off'), ('DEV', 'Development'), ('LAU', 'Launch'), ('SUP', 'Support'), ('TEA', 'Teams'), ('OTH', 'Other')]), ('Sales / Marketing', [('OSH', 'One-Sheets'), ('PDE', 'Pitch / Capabilities Decks'), ('PRO', 'Proposals'), ('OTH', 'Other')]), ('PRPL Brand', [('ASS', 'Assets'), ('SGU', 'Style Guides'), ('TEM', 'Templates'), ('OTH', 'Other')]), ('HR & Paperwork', [('OTH', 'Other')])], max_length=3),
        ),
    ]
