# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 22:04
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20170421_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='filename',
            new_name='name',
        ),
        migrations.AddField(
            model_name='resources',
            name='type',
            field=models.CharField(choices=[('LNK', 'Link'), ('FLE', 'File')], default='FLE', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resources',
            name='url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='resources',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/resources/default.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/parker/Sites/prplapi/files/'), upload_to='resources/'),
        ),
    ]
